#!/bin/bash
# Demo script for US-004: CLI health check before execution

echo "═══════════════════════════════════════════════════════════"
echo "US-004: CLI Health Check Before Execution - Feature Demo"
echo "═══════════════════════════════════════════════════════════"
echo ""

echo "This feature adds a health check before CLI execution to ensure"
echo "the selected CLI is actually working, not just installed."
echo ""

echo "Key Features:"
echo "  ✓ Health check runs before story execution"
echo "  ✓ Results cached for 5 minutes to avoid repeated checks"
echo "  ✓ Failed health check triggers automatic fallback"
echo "  ✓ Comprehensive logging for debugging"
echo ""

echo "─────────────────────────────────────────────────────────────"
echo "1. Health Check Function"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "The checkCLIHealth() method:"
grep -A 20 "private checkCLIHealth" src/utils/ralph-service.ts | head -23
echo ""

echo "─────────────────────────────────────────────────────────────"
echo "2. Cache Implementation (5-minute TTL)"
echo "─────────────────────────────────────────────────────────────"
echo ""
grep -B 1 -A 5 "CLI_HEALTH_CACHE_TTL" src/utils/ralph-service.ts | head -8
echo ""

echo "─────────────────────────────────────────────────────────────"
echo "3. Health Check Before Execution (NEW)"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "In runStoryInternal(), after CLI detection:"
grep -A 15 "Health check the selected CLI before execution" src/utils/ralph-service.ts | head -17
echo ""

echo "─────────────────────────────────────────────────────────────"
echo "4. Fallback Chain Integration"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "The tryFallbackChain() method includes health checks:"
grep -A 10 "// Health check the CLI before using it" src/utils/ralph-service.ts | head -12
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "Flow Diagram:"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "1. detectAICLI() → Check PRD override, global settings, auto-detect"
echo "   └─ Each candidate runs checkCLIHealth()"
echo "      ├─ Cache hit? → Return cached result"
echo "      └─ Cache miss → Run 'cli --version' test"
echo ""
echo "2. runStoryInternal() → Final health check before execution"
echo "   └─ checkCLIHealth(selectedCLI)"
echo "      ├─ Healthy? → Proceed with execution"
echo "      └─ Failed? → Try fallback chain"
echo "         └─ Find healthy alternative or throw error"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "Example Scenarios:"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Scenario 1: CLI installed but not configured"
echo "  - detectAICLI() finds 'claude'"
echo "  - checkCLIHealth() runs 'claude --version'"
echo "  - Result: Fails (not authenticated)"
echo "  - Action: Try next CLI in fallback chain"
echo ""
echo "Scenario 2: All checks pass"
echo "  - Health check passes"
echo "  - Result cached for 5 minutes"
echo "  - Story execution proceeds"
echo ""
echo "Scenario 3: CLI becomes unhealthy between runs"
echo "  - First run: Passes (cached)"
echo "  - 6 minutes later: Cache expired"
echo "  - Second run: Re-checks, detects failure"
echo "  - Action: Automatic fallback triggered"
echo ""

echo "✓ Demo complete!"
